chat/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.messages_page),
]

findntrade/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('my_profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:id>/', views.OtherProfileView.as_view(), name='other_user_profile'),
    path('profile_edit/', views.ProfileUpdateView.as_view(), name='profile edit'),


    path('categories/', views.categories, name='categories'),
    path('categories2/', views.categories2, name='categories2'),
    path('search_result/', views.SearchResultView.as_view(), name='searchresult'),
    path('search_results/', views.search_results, name='searchresult2'),

    path('create_ad/', views.AdCreateView.as_view(), name='create ad'),
    path('edit_ad/<int:pk>/', views.AdEditView.as_view(), name='edit ad'),
    path('ad_list/', views.AdListView.as_view(), name='ad list'),
    path('ad_details/<int:id>/', views.DetailAdView.as_view(), name='ad_details'),

    path('active_ads/', views.ActiveAdListView.as_view(), name='active ads'),
    path('archived_ads/', views.ArchivedAdListView.as_view(), name='archived ads'),
    path('delete_photo/', views.delete_photo, name='delete_photo'),
    path('delete_ad/', views.delete_ad, name='delete_ad'),
    path('archive_ad/', views.archive_ad, name='archive_ad'),
    path('active_ad/', views.active_ad, name='active_ad'),

    path('blog/', views.blog, name='blog'),
    path('blog_article/', views.blog_article, name='blog_article'),
    path('responds/', views.RespondsListView.as_view(), name='responds'),
    path('responds_companies/<int:id>/', views.RespondsCompaniesDetailView.as_view(), name='responds_companies'),
    path('set_state,', views.set_state, name='set_state'),
    path('get_thread/<int:first_id>/<int:second_id>/', views.get_thread, name='get_thread'),
    path('add_responder/', views.add_responders, name='add responder'),
    path('offers/', views.offers, name='offers'),
    path('chatbox/', views.chatbox, name='chatbox'),
    path('support_chat/', views.support_chat, name='support_chat'),
    path('favs/', views.FavouriteAdView.as_view(), name='favs'),
    path('favs_delete/', views.favs_delete, name='favs_delete'),
    path('favs_add/', views.favs_add, name='favs_add'),
    path('about_us/', views.about_us, name='about_us'),

    path('chat/', views.chatt, name='chat'),
    path('contact/', views.contact, name='contact'),
    path('loading/', views.loading, name='loading'),
    path('error/', views.error, name='error'),
    path('payment/', views.payment, name='payment'),
    path('tariff/', views.tariff, name='tariff'),
    path('termscond/', views.termscond, name='termscond'),

    path('forgot1/', views.forgot1, name='forgot1'),
    path('forgot2/', views.forgot2, name='forgot2'),
    path('forgot3/', views.forgot3, name='forgot3'),
    path('congrats_password/', views.congrats_password, name='congrats_password'),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('reset/<str:user>/<str:token>/', views.password_reset_confirm, name="password_reset_confirm"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password


class CustomUserManager(BaseUserManager):
    def create_user(self, email: str, name: str, surname: str, password=None):
        if not email:
            raise ValueError("email field is mandatory")
        elif not name:
            raise ValueError("Name field is mandatory")
        elif not surname:
            raise ValueError("Surname field is mandatory")

        user = self.model(
            email=email,
            name=name,
            surname=surname
        )
        user.password = make_password(password)

        profile = Profile()
        profile.save()

        user.profile = profile
        user.save(using=self._db)
        return user

    def create_superuser(self, email: str, name: str, surname: str, password=None):
        user = self.create_user(
            email=email,
            name=name,
            surname=surname,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


def user_profile_directory_path(instance, filename: str) -> str:
    return f'profile_images/{instance.id}/{filename}'

def user_image_directory_path(instance, filename: str) -> str:
    return f'ad_images/{instance.id}/{filename}'

class Role(models.Model):
    OWNER = "Предприниматель"
    SUPPLIER = "Поставщик"
    choices = [
        (OWNER, "Предприниматель"),
        (SUPPLIER, "Поставщик"),
    ]

class Profile(models.Model):
    id = models.AutoField(primary_key=True, verbose_name="ID")
    city = models.CharField(max_length=15, blank=True, null=True, verbose_name="City")
    date_of_birth = models.DateField(max_length=15, blank=True, null=True, verbose_name='Date of birth')
    company_name=models.CharField(max_length=30, blank=True, null=True, verbose_name="Company name")
    description=models.TextField(blank=True, null=True, verbose_name="Description")
    phone_number = models.CharField(max_length=15, blank=True, null=True, verbose_name="Phone number")
    role = models.CharField(max_length=200, choices=Role.choices, verbose_name="Role")
    image_link = models.ImageField(upload_to=user_profile_directory_path, blank=True, null=True,
                                   verbose_name="Profile image")


class CustomUser(AbstractBaseUser):
    id = models.AutoField(primary_key=True, verbose_name="ID")

    email = models.EmailField(unique=True, verbose_name="Email")
    name = models.CharField(max_length=26, verbose_name="Name")
    surname = models.CharField(max_length=26, verbose_name="Surname")

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Profile")

    reset_password_token = models.UUIDField(blank=True, null=True, default=None, verbose_name="Reset password token")

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True, verbose_name="Last login")

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = ["name", "surname"]

    objects = CustomUserManager()


    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

def user_and_order_directory_path(instance, filename: str) -> str:
    return f'order/{instance.order.creator.username}/{instance.order.id}/{filename}'


def generate_upload_path(instance, filename:str) -> str:
    # Generate a unique filename for the uploaded file
    return f'ad/{instance.user.email}/{instance.id}/{filename}'

class RespondState(models.Model):
    PROCESSING = "На рассмотрении"
    ACCEPTED = "Принят"
    DECLINED = "Отказ"
    choices = [
        (PROCESSING, "На рассмотрении"),
        (ACCEPTED, "Принят"),
        (DECLINED, "Отказ"),
    ]

class Respond(models.Model):
    user = models.ForeignKey(CustomUser, blank=False, null=False, on_delete=models.CASCADE, related_name='Respondent')
    state = models.CharField(max_length=200, choices=RespondState.choices, verbose_name="State")
    create_date= models.DateTimeField(auto_now_add=True, verbose_name="Creation date")
    def __str__(self):

        return self.user.email + " " + self.state
class Category(models.Model):
    name= models.CharField(max_length=50, blank=True, null=True, verbose_name="Category_name")
    slug= models.CharField(max_length=50, blank=True, null=True, verbose_name="Slug")

    def __str__(self):
        return self.name


class Ad(models.Model):
    user= models.ForeignKey(CustomUser, blank=False, null=False, on_delete=models.CASCADE, related_name='creator')
    title= models.CharField(max_length=50, verbose_name="Title")
    company_name= models.CharField(max_length=50, blank=True, null=True, verbose_name="Company_name")
    description= models.TextField(verbose_name="Description")
    image_link = models.ImageField(upload_to=user_image_directory_path, blank=True, null=True,
                                   verbose_name="Ad image")
    cost= models.FloatField(verbose_name="Cost")
    responders= models.ManyToManyField(Respond, blank=True, null=True)
    create_date = models.DateField(auto_now_add=True, verbose_name="Creation date")
    edit_date = models.DateField(auto_now=True, verbose_name="Edit date")
    is_active = models.BooleanField(default=True, verbose_name="Active")
    category=models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title



class FavoriteAd(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'ad')

main/forms.py
from django import forms
from .models import CustomUser, Profile, Role, Ad
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.forms import ImageField, FileInput,ClearableFileInput

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number', 'role','image_link','description','company_name']

        widgets = {
            'phone_number': forms.TextInput(
            attrs={
                'class': 'authorization__wrapper-block-form__pair-input',
                'placeholder': 'Введите номер телефона'
            }),
            'description': forms.Textarea(
                attrs={
                    'style': 'width:350px;'
                }),
            'role': forms.RadioSelect(attrs={'class': 'registration__form__inputs-pair-input-radio'}),
        }

class ProfileEditForm(ProfileForm):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ProfileEditForm, self).__init__(*args, **kwargs)



class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'surname',  'email', 'password']
        
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'authorization__wrapper-block-form__pair-input',
                    'placeholder': 'Введите имя'
                }),
            'surname': forms.TextInput(
                attrs={
                    'class': 'authorization__wrapper-block-form__pair-input',
                    'placeholder': 'Введите фамилию'
                }),
            'email': forms.EmailInput(
                attrs={
                    'class': 'authorization__wrapper-block-form__pair-input',
                    'placeholder': 'Введите почту'
                }),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'authorization__wrapper-block-form__pair-input',
                    'placeholder': 'Введите пароль'
                }),

        }

    def init(self, *args, **kwargs):
        super().init(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-class'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
        return user
    
class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'surname',  'email']
        
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'registration__form__inputs-pair-input',
                    'placeholder': 'Введите имя'
                }),
            'surname': forms.TextInput(
                attrs={
                    'class': 'registration__form__inputs-pair-input',
                    'placeholder': 'Введите фамилию'
                }),
            'email': forms.EmailInput(
                attrs={
                    'class': 'registration__form__inputs-pair-input',
                    'placeholder': 'Введите почту'
                }),
        }


class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['password']
        exclude = ['email']
    
class AdCreateForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ['user', 'title', 'company_name', 'image_link', 'description', 'cost','category']

        widgets = {
            'user': forms.HiddenInput(),
            'title': forms.TextInput(
                attrs={
                    'class': 'text-field__input',
                    'placeholder': "Введите название"
                }
            ),
            'company_name': forms.TextInput(
                attrs={
                    'class': 'text-field__input',
                    'placeholder': "Введите название компании"
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': "Опишите свой товар/услугу (максимум 200 символов)"
                }
            ),
            'cost': forms.NumberInput(
                attrs={
                    'class': 'text-field__input',
                    'placeholder': "Введите цену",
                    'style': "width:50%;"
                }
            ),
            'category':forms.Select(
                attrs={
                    'class':'multiple-select ad_create'
                }
            )
        }

main/templates/main/archived_ads.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Find-n-Trade {% endblock %}
{% block links %}  <link rel="stylesheet" href="{% static 'main/css/style_imported.css' %}">  {% endblock %}

{% block content %}

<body background="{% static 'main/images/bg5.png' %}">
    <main>
      <h1 id="actarchads">Мои объявления</h1>
      <div class="ads-sections">
        <a href="{% url 'active ads'%}"><p class="nav_nonactive">Активные</p></a>
        <a href="{% url 'archived ads'%}"><p >Архивные</p></a>
      </div>
      <div class="adsactive">
        {% for i in object_list %}

          <div class="card">
            <div class="ad_image">
              {% if i.image_link.file is not None     %}

              <img  class="adimg" src="{{i.image_link.url}}" alt="" >
              {% else %}
              <img  class="adimg" src="{% static 'main/img/no-image-removebg-preview.png'%}" alt="" style="
>>>>>>> ce082dae88308b17f1a1f4c6b20062209e8e8807
                 border: solid 1px #CCC">

              {% endif %}
            </div>
            <div class="adtext">
               <a href="{% url 'ad_details' id=i.id %}">  <h4><b>{{i.title}} </b></h4></a>
              <p>{{i.create_date|date:'d/m/Y'}}</p>
            </div>
            <div class="ads-actions">
              <form action="{% url 'active_ad'%}" method="post">
                <input type="hidden" value="{{i.id}}" name="id">
                <button><p style="background-color: #35DABA; color:white;">Восстановить</p></button>
                {% csrf_token %}
              </form>
              <form action="{% url 'delete_ad'%}" method="post">
                <input type="hidden" value="{{i.id}}" name="id">
                <button><p style="background-color: #FF3E3E; color:white;">Удалить</p></button>
                {% csrf_token %}
              </form>
            </div>
          </div>
      {% endfor %}

    </div>
    <div class="pagination" style="margin-top: 30px;">
      <div class="pages">
        {% for page in paginator.page_range %}
          <a href="?page={{page}}"><p class="{% if page_obj.number == page  %}active_page{% endif %}">{{page}}</p></a>
        {% endfor %}
        </div>
     </main>
</body>
{% endblock %}

main/templates/main/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">

    {% block links %} {% endblock %}
</head>

<body>


    <header class="header">

        <div class="sitelogo">
            <a href="{% url 'index' %}">
                <img src="{% static 'main/icons/Find-n-trade.png' %}" alt="">
            </a>
        </div>



        <div class="navigation">

            <input type="checkbox" name="" id="" class="toggle-menu">
            <div class="hamburger"></div>
            <ul class="navmenu">
                <li><a href="{% url 'categories' %}">Категории</a></li>
                <li><a href="{% url 'blog' %}">Блог</a></li>
                <li><a href="{% url 'about_us' %}">О нас</a></li>
                <li><a href="{% url 'contact' %}">Контакты</a></li>
            </ul>
        </div>

        <div class="navicons">
            <a href="#"><img src="{% static 'main/icons/location.png' %}" alt=""></a>
            {% if user.is_authenticated %}
            <a href="{% url 'profile' %}  "><img src="{% static 'main/icons/user.png' %}"></a>
            {% else %}
            <a href="{% url 'register' %} "><img src="{% static 'main/icons/user.png' %}" alt="profile"
                    class="header__settings-profile"></a>
            {% endif %}
        </div>

    </header>


    
    {% block content %}

    {% endblock %}
</body>

</html>

main/templates/main/create_ad.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Find-n-Trade {% endblock %}
{% block links %}  <link rel="stylesheet" href="{% static 'main/css/style_imported.css' %}">  {% endblock %}

{% block content %}

<body background="{% static 'main/images/bg4.png' %}">
    <main>
        <h1 id="newad">Новое объявление</h1>
        <form action="" method="POST" class="newadouterdiv" enctype="multipart/form-data">
          {% csrf_token %}
          <p id="required">*обязательно</p>
          <div class="newadleft">
            <div class="labeloneline">
              <label class="text-field__label" for="name">Название</label>
              <label style="color:#FF3E3E" class="text-field__label" for="name">*
                    {% if form.errors %}
                        {{form.errors}}
                    {% endif %}
            </label>
            </div>
            <select name="user" required="" id="id_user" hidden>
                <option value="{{user.id}}" selected>{{ user.email }}</option>
              
              </select>
            {{form.title}}

              <div class="labeloneline" >
              <label class="text-field__label" for="name">Категория</label>
            </div>
            {{form.category}}

               <div class="labeloneline">
              <label class="text-field__label" for="companyname">Описание</label>
              <label style="color:#FF3E3E" class="text-field__label" for="description">*</label>
            </div>
            {{form.description}}

            <div class="labeloneline">
              <label class="text-field__label" for="name">Цена</label>
              <label style="color:#FF3E3E" class="text-field__label" for="price">*</label>
            </div>
            {{form.cost}}
               <div class="labeloneline">
              <label class="text-field__label" for="name">Фотографии/вложения</label>
            </div>
            <div class="file-upload" style="display:flex;">
                         <div class="picedit">
                         <div class="panel">
                          <div class="button_outer">
                            <div class="btn_upload">
                               {{form.image_link}} Upload Image
                            </div>
                            <div class="processing_bar"></div>
                            <div class="success_box"></div>
                          </div>
                         </div>
                        <div class="error_msg"></div>
                        <div class="uploaded_file_view" id="uploaded_view">
                          <span class="file_remove">X</span>
                        </div>
                        </div>
            </div>
        <button id="publishsubmit" type="submit">Опубликовать</button>
        </form>
      </div>
    </main>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script> var btnUpload = $("#id_image_link"),
    btnOuter = $(".button_outer");
  btnUpload.on("change", function(e){
    var ext = btnUpload.val().split('.').pop().toLowerCase();
    if($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
      $(".error_msg").text("Not an Image...");
    } else {
      $(".error_msg").text("");
      btnOuter.addClass("file_uploading");
      setTimeout(function(){
        btnOuter.addClass("file_uploaded");
      },3000);
      var uploadedFile = URL.createObjectURL(e.target.files[0]);
      setTimeout(function(){
        $("#uploaded_view").append('<img src="'+uploadedFile+'" />').addClass("show");
      },3500);
    }
  });
  $(".file_remove").on("click", function(e){
    $("#uploaded_view").removeClass("show");
    $("#uploaded_view").find("img").remove();
    btnOuter.removeClass("file_uploading");
    btnOuter.removeClass("file_uploaded");
  });</script>
{% endblock %}

main/templates/main/edit_ad.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Find-n-Trade {% endblock %}
{% block links %}  <link rel="stylesheet" href="{% static 'main/css/style_imported.css' %}">  {% endblock %}

{% block content %}

<body background="{% static 'main/images/bg4.png' %}">
    <main>
        <h1 id="newad">Новое объявление</h1>
        <form action="" method="POST" class="newadouterdiv" enctype="multipart/form-data">
          {% csrf_token %}
          <p id="required">*обязательно</p>
          <div class="newadleft">
            <div class="labeloneline">
              <label class="text-field__label" for="name">Название</label>
              <label style="color:#FF3E3E" class="text-field__label" for="name">
                    {% if form.errors %}
                        {{form.errors}}
                    {% endif %}
            </label>
            </div>
            <select name="user" required="" id="id_user" hidden>
                <option value="{{user.id}}" selected>{{ user.email }}</option>

              </select>
            {{form.title}}



               <div class="labeloneline">
              <label class="text-field__label" for="companyname">Описание</label>
              <label style="color:#FF3E3E" class="text-field__label" for="description">*</label>
            </div>
            {{form.description}}

            <div class="labeloneline">
              <label class="text-field__label" for="name">Цена</label>
              <label style="color:#FF3E3E" class="text-field__label" for="price">*</label>
            </div>
            {{form.cost}}
               <div class="labeloneline">
              <label class="text-field__label" for="name">Фотографии/вложения</label>
            </div>
            <div class="file-upload" style="display:flex;">
                         <div class="picedit">
                         <div class="panel">
                          <div class="button_outer">
                            <div class="btn_upload">
                              <input type="file" name="image_link" accept="image/*" id="id_image_link"> Upload Image
                            </div>
                            <div class="processing_bar"></div>
                            <div class="success_box"></div>
                          </div>
                         </div>
                        <div class="error_msg"></div>
                        <div class="uploaded_file_view" id="uploaded_view">
                          <span class="file_remove">X</span>
                        </div>
                        </div>
            </div>


        <button id="publishsubmit" type="submit"><a href="{% url 'active ads' %}">Применить</a> </button>
        </form>
      </div>
    </main>
    <footer class="footer">
        <div class="container">
            <div class="footer__wrapper">
                <div class="footer__links">
                    <div class="footer__links__wrapper">
                        <div class="footer__links-column">
                            <ul class="footer__links-column__list">
                                <li class="footer__links-column__list-item"><a href="{% url 'index' %}" class="footer__links-column__list-item__link">Главное</a></li>
                                <li class="footer__links-column__list-item"><a href="{% url 'blog' %}" class="footer__links-column__list-item__link">Блог</a></li>
                                <li class="footer__links-column__list-item"><a href="{% url 'about_us' %}" class="footer__links-column__list-item__link">О нас</a></li>
                                <li class="footer__links-column__list-item"><a href="{% url 'categories' %}" class="footer__links-column__list-item__link">Категории</a></li>
                                <li class="footer__links-column__list-item"><a href="{% url 'contact' %}" class="footer__links-column__list-item__link">Контакты</a></li>
                            </ul>
                        </div>

                        <div class="footer__links-column">
                            <ul class="footer__links-column__list">
                                <li class="footer__links-column__list-item"><a href="{% url 'searchresult' %}" class="footer__links-column__list-item__link">Объявления</a></li>
                                <li class="footer__links-column__list-item"><a href="{% url 'termscond' %}" class="footer__links-column__list-item__link">Условия оказания услуг</a></li>
                                <li class="footer__links-column__list-item"><a href="#" class="footer__links-column__list-item__link">Условия использования сайта</a></li>
                            </ul>
                        </div>

                        <div class="footer__links-column">
                            <ul class="footer__links-column__list">
                                <li class="footer__links-column__list-item"><a href="{% url 'support_chat' %}" class="footer__links-column__list-item__link">Тех.поддержка</a></li>
                                <li class="footer__links-column__list-item"><a href="#" class="footer__links-column__list-item__link">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                </div>

                <div class="footer__social">
                    <a href="{% url 'index' %}"><div class="footer__social-logo">FIND-N-TRADE</div></a>

                    <div class="footer__social__items">
                        <a href="https://www.instagram.com/"><img src="{% static 'main/icons/insta.svg' %}" alt="instagram" class="footer__social-item">
                        <a href="https://www.youtube.com/"><img src="{% static 'main/icons/youtube.svg' %}" alt="youtube" class="footer__social-item">
                        <a href="https://ru-ru.facebook.com/"><img src="{% static 'main/icons/facebook.svg' %}" alt="facebook" class="footer__social-item">
                    </div>
                </div>
            </div>

            <div class="dash"></div>

            <div class="footer__credit">Ⓒ 2022 Группа компании Find-n-Trade</div>
        </div>
    </footer>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script> var btnUpload = $("#id_image_link"),
    btnOuter = $(".button_outer");
  btnUpload.on("change", function(e){
    var ext = btnUpload.val().split('.').pop().toLowerCase();
    if($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
      $(".error_msg").text("Not an Image...");
    } else {
      $(".error_msg").text("");
      btnOuter.addClass("file_uploading");
      setTimeout(function(){
        btnOuter.addClass("file_uploaded");
      },3000);
      var uploadedFile = URL.createObjectURL(e.target.files[0]);
      setTimeout(function(){
        $("#uploaded_view").append('<img src="'+uploadedFile+'" />').addClass("show");
      },3500);
    }
  });
  $(".file_remove").on("click", function(e){
    $("#uploaded_view").removeClass("show");
    $("#uploaded_view").find("img").remove();
    btnOuter.removeClass("file_uploading");
    btnOuter.removeClass("file_uploaded");
  });</script>
{% endblock %}

main/templates/main/forgot_password_1.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ошибка</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body class="password_background">
    <div class="password__container">
        <a href="{% url 'index' %}" class="password__container-heading">FIND-N-TRADE</a>
        <form action="{% url 'reset_password' %}" method="post" class="password__container__wrapper">
            <div class="password__container__wrapper-block">
                <div class="password__container__wrapper-block-heading">Сброс пароля</div>
                <input type="text" class="password__container__wrapper-block-input" placeholder="Email" name="email">
            </div>
            <button class="password__container__wrapper-button" type="submit">
                Продолжить
            </button>
            {% csrf_token %}
        </form>
    </div>
</body>
</html>

main/templates/main/forgot_password_2.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ошибка</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body class="password_background">
    <div class="password__container">
        <a href="{% url 'index' %}" class="password__container-heading">FIND-N-TRADE</a>
        <div class="password__container__wrapper">
            <div class="password__container__wrapper-block">
                <div class="password__container__wrapper-block-heading">Сброс пароля</div>
                <input type="text" class="password__container__wrapper-block-input" placeholder="Введите код активации">
            </div>
            <button class="password__container__wrapper-button">
                 <a href="{% url 'forgot3'%}">Продолжить
            </button></a>
        </div>
    </div>
</body>
</html>